export type UiDebugScope = 'home' | 'project';
export type UiDebugSelection = {
  id: string;
  state: string;
  scope: UiDebugScope;
  theme: 'dark' | 'light';
};
export type UiDebugEntry = {
  id: string;
  label: string;
  code: string;
  source: string;
  group: string;
  scopes: UiDebugScope[];
  selector: string;
  states: string[];
};
const home: UiDebugScope[] = ['home'];
const project: UiDebugScope[] = ['project'];
const both: UiDebugScope[] = ['home', 'project'];
const entry = (
  id: string,
  label: string,
  code: string,
  file: string,
  group: string,
  scopes: UiDebugScope[],
  selector: string,
  states = ['default'],
): UiDebugEntry => ({
  id,
  label,
  code,
  source: `src/ui/${file}.tsx`,
  group,
  scopes,
  selector,
  states,
});

// Every preview uses the production component. Inline surfaces retain their
// actual state identifier; never invent a component name for an inline view.
export const UI_DEBUG_ENTRIES: UiDebugEntry[] = [
  entry(
    'flow-controls',
    '캔버스 확대·맞춤',
    'Controls',
    'App',
    '캔버스',
    project,
    '.react-flow__controls',
  ),
  entry(
    'minimap',
    '캔버스 미니맵',
    'MiniMap',
    'App',
    '캔버스',
    project,
    '.react-flow__minimap',
  ),
  entry(
    'guides',
    '스마트 정렬 가이드',
    'WorkspaceCanvas / guides',
    'App',
    '캔버스',
    project,
    '.snap-guide',
  ),
  entry(
    'home',
    '홈 화면',
    'ProjectHome',
    'ProjectHome',
    '홈',
    home,
    '.project-home',
    ['default', 'list', 'empty', 'loading', 'error'],
  ),
  entry(
    'home-sidebar',
    '홈 사이드바·폴더',
    'ProjectHome / .home-sidebar',
    'ProjectHome',
    '홈',
    home,
    '.home-sidebar',
  ),
  entry(
    'home-controls',
    '검색·정렬·필터',
    'ProjectHome / .home-list-toolbar',
    'ProjectHome',
    '홈',
    home,
    '.home-list-toolbar',
    ['default', 'list'],
  ),
  entry(
    'home-project',
    '프로젝트 카드',
    'ProjectHome / .home-project-card',
    'ProjectHome',
    '홈',
    home,
    '.home-project-card',
    ['default', 'list'],
  ),
  entry(
    'home-menu',
    '프로젝트·폴더 메뉴',
    'HomeContextMenu',
    'HomeOrganizationControls',
    '메뉴',
    home,
    '.home-context-menu',
    ['project', 'folder'],
  ),
  entry(
    'home-organize',
    '프로젝트·폴더 정리 팝업',
    'HomeOrganizationDialog',
    'HomeOrganizationControls',
    '팝업',
    home,
    '[data-ui-id="home-organize"]',
    [
      'rename-project',
      'move-project',
      'create-folder',
      'rename-folder',
      'remove-folder',
      'busy',
      'error',
    ],
  ),
  entry(
    'home-create',
    '새 프로젝트·서버 주소',
    'ProjectHome / .home-create-dialog',
    'ProjectHome',
    '팝업',
    home,
    '.home-create-dialog',
    ['create', 'server', 'busy', 'error'],
  ),
  entry(
    'web-viewer',
    '웹 뷰어',
    'WebViewerDialog',
    'WebViewerDialog',
    '팝업',
    home,
    '.web-viewer-dialog',
    ['configured', 'unconfigured', 'error'],
  ),
  entry(
    'canvas',
    '프로젝트 캔버스',
    'WorkspaceCanvas',
    'App',
    '캔버스',
    project,
    '.canvas-shell',
    ['default', 'empty'],
  ),
  entry(
    'top-tools',
    '상단 도구',
    'WorkspaceCanvas / .floating-header',
    'App',
    '도구',
    project,
    '.floating-header',
  ),
  entry(
    'bottom-tools',
    '하단 도구',
    'WorkspaceCanvas / .bottom-toolbar',
    'App',
    '도구',
    project,
    '.bottom-toolbar',
  ),
  entry(
    'canvas-utility',
    '확대·축소·실행 취소',
    'WorkspaceCanvas / .canvas-utility',
    'App',
    '도구',
    project,
    '.canvas-utility',
  ),
  entry(
    'note-drawing',
    '새 메모 드래그 영역',
    'WorkspaceCanvas / noteDraft',
    'App',
    '도구',
    project,
    '.note-drawing-preview',
  ),
  entry(
    'selection',
    '선택·정렬 도구',
    'WorkspaceCanvas / .selection-context',
    'App',
    '도구',
    project,
    '.selection-context',
    ['single', 'multiple', 'arrange'],
  ),
  entry(
    'ui-hidden',
    '도구 숨김·복원',
    'WorkspaceCanvas / uiHidden',
    'App',
    '도구',
    project,
    '.ui-reveal-button',
  ),
  entry(
    'document',
    '메모·문서·참고 카드',
    'DocumentCard',
    'App',
    '카드',
    project,
    '.document-card',
    ['idea', 'system', 'reference', 'collapsed', 'locked', 'new'],
  ),
  entry(
    'image',
    '이미지 카드',
    'ProjectImage / DocumentCard',
    'App',
    '카드',
    project,
    '.project-image, .project-image-placeholder',
    ['default', 'error'],
  ),
  entry(
    'section',
    '섹션 카드',
    'SectionCard',
    'App',
    '카드',
    project,
    '.section-card',
    ['default', 'selected', 'locked'],
  ),
  entry(
    'preview',
    'HTML 결과 카드',
    'PreviewCard',
    'App',
    '카드',
    project,
    '.preview-card',
    ['default', 'collapsed', 'settings', 'locked'],
  ),
  entry(
    'markdown',
    'Markdown 표시',
    'DocumentMarkdown',
    'DocumentMarkdown',
    '편집기',
    project,
    '.markdown-body',
  ),
  entry(
    'editor',
    'Markdown 편집기',
    'MarkdownEditor',
    'MarkdownEditor',
    '편집기',
    project,
    '.markdown-editor',
    [
      'default',
      'source',
      'focus',
      'text',
      'insert',
      'more',
      'slash',
      'locked',
      'warning',
    ],
  ),
  entry(
    'tabs',
    '캔버스 탭·관리',
    'CanvasTabs',
    'CanvasTabs',
    '캔버스',
    project,
    '.canvas-tabs',
    ['default', 'add', 'manage', 'busy', 'error'],
  ),
  entry(
    'navigator',
    '캔버스 탐색',
    'CanvasNavigator',
    'CanvasOverlays',
    '검색',
    project,
    '.canvas-navigator',
    ['default', 'empty'],
  ),
  entry(
    'find',
    '본문 검색',
    'CanvasFind',
    'CanvasFind',
    '검색',
    project,
    '.canvas-find',
  ),
  entry(
    'command',
    '명령 검색',
    'CommandPalette',
    'CanvasOverlays',
    '검색',
    project,
    '.command-palette',
    ['default', 'empty'],
  ),
  entry(
    'shortcuts',
    '단축키 안내',
    'ShortcutDialog',
    'CanvasOverlays',
    '팝업',
    project,
    '.shortcut-dialog',
  ),
  entry(
    'compare',
    'HTML 버전 비교',
    'CompareDialog',
    'CanvasOverlays',
    '팝업',
    project,
    '.compare-dialog',
    ['default', 'empty'],
  ),
  entry(
    'settings',
    '설정 및 도구',
    'WorkspaceCanvas / settingsOpen',
    'App',
    '도구',
    project,
    '.canvas-settings',
  ),
  entry(
    'inspector',
    '상세 정보',
    'WorkspaceCanvas / inspectorId',
    'App',
    '도구',
    project,
    '.object-inspector',
    ['document', 'section', 'html'],
  ),
  entry(
    'collaboration',
    '협업·참여·복구',
    'CollaborationPanel',
    'CollaborationPanel',
    '협업',
    both,
    '.collaboration-dialog',
    [
      'create',
      'join',
      'recover',
      'admin',
      'editor',
      'viewer',
      'offline',
      'remove',
      'leave',
      'recovery',
      'test-users',
      'busy',
      'error',
    ],
  ),
  entry(
    'offline',
    '연결·동기화·충돌',
    'OfflineStatus',
    'OfflineStatus',
    '협업',
    project,
    '.offline-status',
    ['offline', 'pending', 'expired', 'conflict'],
  ),
  entry(
    'update',
    '앱 업데이트',
    'UpdatePanel',
    'UpdatePanel',
    '업데이트',
    both,
    '.update-dialog',
    [
      'idle',
      'checking',
      'downloading',
      'current',
      'ready',
      'installing',
      'error',
      'unconfigured',
      'unavailable',
    ],
  ),
  entry(
    'update-notice',
    '업데이트 알림',
    'UpdatePanel / .update-notice',
    'UpdatePanel',
    '업데이트',
    both,
    '.update-notice',
    ['ready', 'error'],
  ),
  entry(
    'update-restarting',
    '재시작 안내',
    'WorkspaceCanvas / updateRestarting',
    'App',
    '업데이트',
    project,
    '.update-restarting',
  ),
  entry(
    'ai-request',
    'gamejam! 실행 설정',
    'WorkspaceCanvas / aiRequest',
    'App',
    'AI',
    project,
    '.ai-request-dialog',
    [
      'organize',
      'implement',
      'both',
      'html',
      'busy',
      'error',
      'empty-instructions',
      'no-steps',
      'invalid-model',
    ],
  ),
  entry(
    'ai-status',
    'AI 연결 설정',
    'WorkspaceCanvas / codexStatusOpen',
    'App',
    'AI',
    project,
    '.codex-dialog',
    ['connected', 'unavailable', 'busy'],
  ),
  entry(
    'ai-run',
    'AI 작업·로그',
    'WorkspaceCanvas / codexRun',
    'App',
    'AI',
    project,
    '.codex-run-panel',
    [
      'starting',
      'running',
      'validating',
      'completed',
      'failed',
      'cancelled',
      'collapsed',
    ],
  ),
  entry(
    'ai-details',
    'AI 작업 상세',
    'AiTaskDetails',
    'AiTaskDetails',
    'AI',
    project,
    '.ai-task-details',
    ['default', 'failed', 'missing'],
  ),
  entry(
    'completion',
    'AI 완료 알림',
    'WorkspaceCanvas / completion',
    'App',
    'AI',
    project,
    '.ai-completion-toast',
    ['completed', 'failed'],
  ),
  entry(
    'history',
    '히스토리',
    'WorkspaceCanvas / historyOpen',
    'App',
    '히스토리',
    project,
    '.history-panel',
    ['default', 'empty', 'detail', 'ai', 'error'],
  ),
  entry(
    'history-confirm',
    '히스토리 복원 확인',
    'WorkspaceCanvas / historyConfirm',
    'App',
    '히스토리',
    project,
    '[data-ui-id="history-confirm"] [aria-modal="true"]',
    ['default', 'busy'],
  ),
  entry(
    'canvas-menu',
    '빈 캔버스 메뉴',
    'WorkspaceCanvas / contextMenu',
    'App',
    '메뉴',
    project,
    '[data-ui-id="canvas-menu"]',
  ),
  entry(
    'document-menu',
    '문서 메뉴',
    'WorkspaceCanvas / documentContextMenu',
    'App',
    '메뉴',
    project,
    '[data-ui-id="document-menu"]',
    ['default', 'locked'],
  ),
  entry(
    'section-menu',
    '섹션 메뉴',
    'WorkspaceCanvas / sectionContextMenu',
    'App',
    '메뉴',
    project,
    '[data-ui-id="section-menu"]',
  ),
  entry(
    'preview-menu',
    'HTML 메뉴',
    'WorkspaceCanvas / previewContextMenu',
    'App',
    '메뉴',
    project,
    '[data-ui-id="preview-menu"]',
    ['default', 'locked'],
  ),
  entry(
    'result-folder',
    '결과물 폴더 분류·정리',
    'ResultFolderDialog',
    'ResultFolderDialog',
    '팝업',
    project,
    '[aria-label="결과물 폴더 정리"]',
    ['move', 'legacy', 'busy'],
  ),
  entry(
    'import',
    '파일 불러오기',
    'WorkspaceCanvas / importTarget',
    'App',
    '팝업',
    project,
    '[data-ui-id="import"] [aria-modal="true"]',
    ['default', 'busy', 'error'],
  ),
  entry(
    'canvas-move',
    '다른 캔버스로 이동',
    'WorkspaceCanvas / movingCanvasItems',
    'App',
    '팝업',
    project,
    '[data-ui-id="canvas-move"] [aria-modal="true"]',
    ['default', 'busy'],
  ),
  entry(
    'section-create',
    '새 섹션',
    'WorkspaceCanvas / sectionDialogOpen',
    'App',
    '팝업',
    project,
    '[data-ui-id="section-create"] [aria-modal="true"]',
  ),
  entry(
    'section-rename',
    '섹션 이름 변경',
    'WorkspaceCanvas / sectionRename',
    'App',
    '팝업',
    project,
    '[data-ui-id="section-rename"] [aria-modal="true"]',
  ),
  entry(
    'membership',
    '섹션 소속 변경',
    'WorkspaceCanvas / membershipPrompt',
    'App',
    '팝업',
    project,
    '[data-ui-id="membership"] [aria-modal="true"]',
    ['add', 'remove', 'move'],
  ),
  entry(
    'section-action',
    '섹션 해제·삭제',
    'WorkspaceCanvas / sectionActionPrompt',
    'App',
    '팝업',
    project,
    '[data-ui-id="section-action"] [aria-modal="true"]',
    ['ungroup', 'delete'],
  ),
  entry(
    'delete',
    '파일 삭제 확인',
    'WorkspaceCanvas / deletePrompt',
    'App',
    '팝업',
    project,
    '[data-ui-id="delete"] [aria-modal="true"]',
    ['document', 'html', 'image'],
  ),
  entry(
    'delete-many',
    '다중 삭제 확인',
    'WorkspaceCanvas / deleteManyPrompt',
    'App',
    '팝업',
    project,
    '[data-ui-id="delete-many"] [aria-modal="true"]',
  ),
  entry(
    'blocked',
    '작업 차단 안내',
    'WorkspaceCanvas / blockedMessage',
    'App',
    '팝업',
    project,
    '[data-ui-id="blocked"] [aria-modal="true"]',
  ),
  entry(
    'notice',
    '상태 메시지',
    'WorkspaceCanvas / .status-toast',
    'App',
    '알림',
    project,
    '.status-toast',
    ['default', 'error'],
  ),
];

export function uiDebugEntries(scope: UiDebugScope) {
  return UI_DEBUG_ENTRIES.filter((item) => item.scopes.includes(scope));
}
export function validUiDebugSelection(
  value: unknown,
): value is UiDebugSelection {
  if (!value || typeof value !== 'object') return false;
  const item = value as UiDebugSelection;
  return (
    (item.scope === 'home' || item.scope === 'project') &&
    (item.theme === 'dark' || item.theme === 'light') &&
    uiDebugEntries(item.scope).some(
      (entry) => entry.id === item.id && entry.states.includes(item.state),
    )
  );
}
